services:
  - type: web
    name: fakt-checker-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_API_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: GOOGLE_FACT_CHECK_API_KEY
        sync: false
